SKYMARK_VTC_SMART_SCHOLAR_ACADEMY/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('skymarkApp.urls',  namespace='skymarkApp')),
    path('skymark-api/', include('skymarkApi.urls',  namespace='skymarkApi')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

skymarkApi/urls.py
from django.urls import path
from . import views

app_name = 'api'
urlpatterns = [
    # dennis ivy
    path('', views.getDataFromManageClassTable,
         name='getDataFromManageClassTable'),
    path('post-class', views.postDataToManageClassTable,
         name='postDataToManageClassTable'),


    #     not dennis  ivy
    path('modify-class<str:id>/', views.getOrPutOrDeleteDataFromManageClassTable)
]

skymarkApp/urls.py
from django.urls import path, include
from . import views

app_name = 'skymarkApp'

urlpatterns = [
    path('', views.loginPage, name="loginPage"),
    path('dashboard-page', views.dashboardPage, name="dashboardPage"),
    path('manage-classes', views.manageClassesPage, name="manageClassesPage"),
    path('manage-courses', views.ManageCoursesPage, name="ManageCoursesPage"),
    path('manage-students', views.manageStudentsDetailsPage,
         name="manageStudentsDetailsPage"),
    path('manage-staff', views.manageStaffDetailsPage,
         name="manageStaffDetailsPage"),
    path('manage-lesson', views.manageLessonToughtAtCollegePage,
         name="manageLessonToughtAtCollegePage"),
    path('logout-user', views.logOutUser, name="logOutUser"),

]

templates/skymarkPages/Dashboard/dashboardPage.html
{% extends './base.html' %}
{% load static %}
{% block title %} Dashboard{% endblock %}
{% block content %}
{% if get_staff_permision.staff_can_add_or_edit_or_delete_classes == True %}
<div class="container-fluid" id="container-wrapper">
  <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="./">Home</a></li>
      <li class="breadcrumb-item active" aria-current="page">Dashboard</li>
    </ol>
  </div>

  <div class="row mb-3">
    <!-- Earnings (Monthly) Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
      <div class="card h-100">
        <div class="card-body">
          <div class="row align-items-center">
            <div class="col mr-2">
              <div class="text-xs font-weight-bold text-uppercase mb-1">Total  students</div>
              <div class="h5 mb-0 font-weight-bold text-gray-800">{{count_all_students}}</div>
            </div>
            <div class="col-auto">
              <i class="fas fas fas fa-user-alt fa-2x text-primary"></i>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Earnings (Annual) Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
      <div class="card h-100">
        <div class="card-body">
          <div class="row no-gutters align-items-center">
            <div class="col mr-2">
              <div class="text-xs font-weight-bold text-uppercase mb-1"> Total staff </div>
              <div class="h5 mb-0 font-weight-bold text-gray-800">{{count_all_staff}}</div>
              <!-- <div class="mt-2 mb-0 text-muted text-xs">
                <span class="text-success mr-2"><i class="fas fa-arrow-up"></i> 12%</span>
                <span>Since last years</span>
              </div> -->
            </div>
            <div class="col-auto">
              <i class="fas fas fas fa-user-check fa-2x text-success"></i>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- New User Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
      <div class="card h-100">
        <div class="card-body">
          <div class="row no-gutters align-items-center">
            <div class="col mr-2">
              <div class="text-xs font-weight-bold text-uppercase mb-1">Courses</div>
              <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">{{count_all_courses}}</div>
              <!-- <div class="mt-2 mb-0 text-muted text-xs">
                <span class="text-success mr-2"><i class="fas fa-arrow-up"></i> 20.4%</span>
                <span>Since last month</span>
              </div> -->
            </div>
            <div class="col-auto">
              <i class="fas fas fas fa-book-open fa-2x text-info"></i>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Pending Requests Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
      <div class="card h-100">
        <div class="card-body">
          <div class="row no-gutters align-items-center">
            <div class="col mr-2">
              <div class="text-xs font-weight-bold text-uppercase mb-1">Student Graduated</div>
              <div class="h5 mb-0 font-weight-bold text-gray-800">30+</div>
            </div>
            <div class="col-auto">
              <i class="fas fas fas fa-graduation-cap fa-2x text-success"></i>
            </div>
          </div>
        </div>
      </div>
    </div>
   
 

   
  </div>
  

</div>
<div class="staff_todo_list_table">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-8">
        <div class="table_section">
          <div class="col-lg-12">
            <div class="card mb-4">
              <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary"> Sessions taught</h6>
              </div>
              <div class="table-responsive p-3">
                <table class="table align-items-center table-flush table-hover" id="dataTableHover">
                  <thead class="thead-light">
                    <tr>
                      <th>#</th>
                      <th>Topic </th>
                      <th>Remark</th>
                      <th>Date</th>
                      <!-- <th>Registered by</th> -->
                      <th>Action</th>
                    </tr>
                  </thead>
                  <tfoot>
                    <tr>
                      <th>#</th>
                      <th>Topic</th>
                      <th>Remark</th>
                      <th>Date</th>
                      <!-- <th>Registered by</th> -->
                      <th>Action</th>
                    </tr>
                  </tfoot>
                  {% if count_all_lessons %}
                  <tbody>
                    {% for lesson in get_all_lessons %}
                    <tr>
                      <td>{{forloop.counter}}</td>
                      <td> {{ lesson.topic_covered}}</td>
                      
                      <td>{{lesson.remark}}</td>
                      <td>{{lesson.date}}</td>
                      <!-- <td>{{classes.registered_by}}</td> -->
                      <td>
                        <a data-toggle="modal" data-target="#productSoldDetailViewModal{{product_sold.id}}" class="btn btn-sm btn-outline-primary text-primary"><i class="fas fas fa-eye"></i></a>
                        <!-- update button is here  -->
                        <!-- <a  data-toggle="modal" data-target="#updateproductSoldModal{{product_sold.id}}"
                        class="btn btn-sm btn-outline-warning"  ><i class="fas fas fas fa-pen"></i></a> -->
                     
                      </td>
                    </tr> 
                    {% endfor %}  
                   
                    
                    
                  </tbody>
                  {% endif %}
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="row mb-3">
          <p class="pl-4"><strong>Today <code> {{today_date }} </code> Student Attendence.</strong></p>
            <hr >

          <div class="col-xl-12 col-md-12 d-block">
            <div class="card h-100">
              <div class="card-body">
                <div class="row align-items-center">
                  <div class="col mr-2">
                    <div class="text-xs font-weight-bold text-uppercase mb-1"> Present</div>
                    {% if count_all_student_present_today == 0 %}
                    <div class="h5 mb-0 font-weight-bold text-gray-800">-</div>
                    {% else %}
                    <div class="h5 mb-0 font-weight-bold text-gray-800">{{count_all_student_present_today}}</div>

                    {% endif %}
                    <!-- <div class="mt-2 mb-0 text-muted text-xs">
                      <span class="text-success mr-2"><i class="fa fa-arrow-up"></i> 3.48%</span>
                      <span>Ago</span>
                    </div> -->
                  </div>
                  <div class="col-auto">
                    <i class="fas fas fa-user fa-2x text-success"></i>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-xl-12 col-md-12  d-block">
            <div class="card h-100">
              <div class="card-body">
                <div class="row align-items-center">
                  <div class="col mr-2">
                    <div class="text-xs font-weight-bold text-uppercase mb-1"> Absents</div>
                    {% if count_all_student_absent_today == 0 %}
                    <div class="h5 mb-0 font-weight-bold text-gray-800">-</div>
                    {% else %}
                    <div class="h5 mb-0 font-weight-bold text-gray-800">{{count_all_student_absent_today}}</div>

                    {% endif %}
                    <!-- <div class="mt-2 mb-0 text-muted text-xs">
                      <span class="text-success mr-2"><i class="fa fa-arrow-up"></i> 3.48%</span>
                      <span>Ago</span>
                    </div> -->
                  </div>
                  <div class="col-auto">
                    <i class="fas fas fa-user fa-2x text-warning"></i>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% else %}
<div class="container-fluid" id="container-wrapper">
  <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="./">Home</a></li>
      <li class="breadcrumb-item active" aria-current="page">Dashboard</li>
    </ol>
  </div>

  <div class="row mb-3">
    <p class="pl-4"><strong>Today <code> {{today_date }} </code> Student Attendence.</strong></p>
          <hr >
    <div class="col-md-12">
      <div class="row mb-3">
        
        <div class="col-xl-6 col-md-6 d-block">
          <div class="card h-100">
            <div class="card-body">
              <div class="row align-items-center">
                <div class="col mr-2">
                  <div class="text-xs font-weight-bold text-uppercase mb-1"> Present</div>
                    {% if count_all_student_present_today_specific_class == 0 %}
                    <div class="h5 mb-0 font-weight-bold text-gray-800">-</div>
                    {% else %}
                    <div class="h5 mb-0 font-weight-bold text-gray-800">{{count_all_student_present_today_specific_class}}</div>

                    {% endif %}
                  <!-- <div class="mt-2 mb-0 text-muted text-xs">
                    <span class="text-success mr-2"><i class="fa fa-arrow-up"></i> 3.48%</span>
                    <span>Ago</span>
                  </div> -->
                </div>
                <div class="col-auto">
                  <i class="fas fas fa-user fa-2x text-success"></i>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-xl-6 col-md-6  d-block">
          <div class="card h-100">
            <div class="card-body">
              <div class="row align-items-center">
                <div class="col mr-2">
                  <div class="text-xs font-weight-bold text-uppercase mb-1"> Absents</div>
                  {% if count_all_student_absent_today_specific_class == 0 %}
                  <div class="h5 mb-0 font-weight-bold text-gray-800">-</div>
                  {% else %}
                  <div class="h5 mb-0 font-weight-bold text-gray-800">{{count_all_student_absent_today_specific_class}}</div>

                  {% endif %}
                  <!-- <div class="mt-2 mb-0 text-muted text-xs">
                    <span class="text-success mr-2"><i class="fa fa-arrow-up"></i> 3.48%</span>
                    <span>Ago</span>
                  </div> -->
                </div>
                <div class="col-auto">
                  <i class="fas fas fa-user fa-2x text-warning"></i>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="get_all_students_by_its_course">
  {% include './datatables.html'%}
</div>
{% endif %}
<!-- <script>
  window.setTimeout(function () {
    location.href = "{% url 'skymarkApp:dashboardPage' %}";
},5000); // refresh/redirect after 5 seconds.
</script> -->
{% endblock %}

templates/skymarkPages/Dashboard/datatables.html
<div class="col-lg-12">
  <div class="card mb-4">
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
      <h6 class="m-0 font-weight-bold text-primary">List of  Students</h6>
    </div>
    <div class="table-responsive p-3">
      <table class="table align-items-center table-flush table-hover" id="dataTableHover"  >
        <thead class="thead-light">
          <tr>
            <!-- <th>#</th> -->
            <th>name</th>
            <th>course</th>
            <th>Status</th>
            <!-- <th>Registered by</th> -->
            <th>Action</th>
          </tr>
        </thead>
        <tfoot>
          <tr>
            <!-- <th>#</th> -->
            <th>name</th>
            <th>course</th>
            <th>Status</th>
            <!-- <th>Registered by</th> -->
            <th>Action</th>
          </tr>>
          </tr>
        </tfoot>
        {% if get_all_students_by_its_course %}
        <tbody>
          {% for student in get_all_students_by_its_course %}
          <tr hx-get="{% url 'skymarkApp:dashboardPage' %}" hx-trigger="every 1s" hx-swap="innerHTML">
            <!-- <td>{{forloop.counter}}</td> -->
            <td> {{ student.student_full_name}}</td>
            
            <td>{{student.course_name}}</td>
            {% if student.today_attendence == False %}
            <td>Today Student is <code>Absents</code> </td>
            {% endif %}

            {% if student.today_attendence == True %}
            <td>Today Student is <mark>Present</mark> </td>
            {% endif %}
            <!-- <td>{{classes.registered_by}}</td> -->
            <td>
              <a data-toggle="modal" data-target="#studentDetailModal{{student.id}}" class="btn btn-sm btn-outline-info text-info"><i class="fas fas fa-eye"></i></a>
              
           

              
              

              <a data-toggle="modal" data-target="#studentsAttendenceModal{{student.id}}" class="btn btn-sm btn-outline-primary text-primary"><i class="fas fas far fa-plus-square"> Attendence</i></a>
              {% include './studentsAttendenceModal.html' %}
      

             
              
              <!-- <a data-toggle="modal" data-target="#productSoldDetailViewModal{{student.id}}" class="btn btn-sm btn-outline-info text-primary"><i class="fas fas far fa-plus-square"> results</i></a> -->
              <!-- <a  data-toggle="modal" data-target="#deleteProductSoldModal" class="btn btn-sm btn-outline-danger"><i class="fas fas fas far fa-trash-alt"></i></a> -->
            </td>
          </tr> 
          {% include './studentDetailModal.html' %}
          {% endfor %}  
         
          
          
        </tbody>
        {% endif %}

      </table>
    </div>
  </div>
</div>

templates/skymarkPages/Dashboard/logoutModal.html
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabelLogout"
aria-hidden="true">
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title" id="exampleModalLabelLogout">Ohh No!</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      <p>Are you sure you want to logout?</p>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-outline-primary" data-dismiss="modal">Cancel</button>
      <a href="{% url 'skymarkApp:logOutUser' %}" class="btn btn-primary">Logout</a>
    </div>
  </div>
</div>
</div>

templates/skymarkPages/Dashboard/studentDetailModal.html
<div class="modal fade" id="studentDetailModal{{student.id}}">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">Student <code>{{student.student_full_name}}</code> Detail information</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <!-- Modal body -->
      <div class="modal-body">
        <div class="row">
          <div class="col-lg-12">
              
              <!-- Timeline -->
              <ul class="timeline">
                  <li class="timeline-item bg-white rounded mx-3 mb-2 p-4 shadow">
                      <div class="timeline-arrow"></div>
                      <div class="item" style="display:flex;justify-content:space-between;">
                        <div class="image">
                          <img src="{{student.student_image.url }}" class="img-fluid" width="200px">
                        </div>
                        <div class="informations pl-2 m-1" style="display:inline-block;width:100%">
                          <h2 class="h5 mb-0">Student Basic information</h2><span class="small text-gray"><i class="fa fa-clock-o mr-1"></i>Student name : <mark>{{student.student_full_name}}</mark></span>
    `                       <hr class="sidebar-divider">
                         
                          <span class="text-small d-block mt-0 font-weight-light">Sex: <code>{{student.gender}}</code></span>
                          <span class="text-small d-block font-weight-light">Course: <code>{{student.course_name}}</code></span>
                          <span class="text-small d-block font-weight-light">Date of admission: <code>{{student.admission_date}}</code></span>
                          <span class="text-small d-block font-weight-light">Phone number: <code> {{student.phone_number}}</code></span>
                          <span class="text-small d-block font-weight-light">Email: <code> {{student.email}}</code></span>
                        </div>
                      </div>
                      
                  </li>
                  <li class="timeline-item bg-white rounded mx-3 mb-2 p-4 shadow">
                      <div class="timeline-arrow"></div>
                      <h2 class="h5 mb-0">Parent Details</h2><span class="small text-gray"><i class="fa fa-clock-o mr-1"></i>name : {{student.parent_name}}</span>
    `                       <hr class="sidebar-divider">
                      
                      <p class="text-small mt-2 font-weight-light">Phone number : {{student.parent_phone_number}}</p>
                      <!-- <p class="text-small mt-2 font-weight-light">Libero expedita explicabo eius fugiat quia aspernatur autem laudantium error architecto recusandae natus sapiente sit nam eaque, consectetur porro molestiae ipsam! Deleniti.</p> -->
                  </li>
                  <li class="timeline-item bg-white rounded mx-3 mb-2 p-4 shadow">
                      <div class="timeline-arrow"></div>
                      <h2 class="h5 mb-0">Fees paid for <code>{{student.course_name}}</code> </h2><span class="small text-gray"><i class="fa fa-clock-o mr-1"></i></span>
    `                  <hr class="sidebar-divider">
                      {% for fee in get_all_fee_from_all_students %}
                      {% if fee.student_full_name.id == student.id %}
                      <div class="item" style="display:flex;justify-content:space-between;">
                        <div class="dates">
                         <p>{{fee.date }}</p>

                        </div>
                        <div class="informations pl-2 m-1" style="display:inline-block;width:100%;text-align: right;">
                          <p class="text-small d-block mt-0 font-weight-light">{{fee.amount_paid}} Tsh</p>
                          <!-- <p class="text-small d-block font-weight-light">{{student.course_name}}</p> -->
    `                  <hr class="sidebar-divider">
                          
                        </div>
                      </div>
                      {% endif %}
                      {% endfor %}
                  </li>

                  <li class="timeline-item bg-white rounded mx-3 mb-2 p-4 shadow">
                      <div class="timeline-arrow"></div>
                      <h2 class="h5 mb-0">Student attendance </h2><span class="small text-gray"><i class="fa fa-clock-o mr-1"></i></span>
    `                  <hr class="sidebar-divider">
                      {% for attendance in get_attendance_for_all_student %}
                      {% if attendance.student_name.id == student.id %}
                      <div class="item" style="display:flex;justify-content:space-between;">
                        <div class="dates">
                         <p>{{attendance.date }}</p>

                        </div>
                        <div class="informations pl-2 m-1" style="display:inline-block;width:100%;text-align: right;">
                          {% if attendance.attendance_status == True %}
                          <p class="text-small text-success d-block mt-0 font-weight-light">presents </p>
                          {% else %}
                          <p class="text-small text-danger d-block mt-0 font-weight-light">Absents </p>

                          {% endif %}
                          <!-- <p class="text-small d-block font-weight-light">{{student.course_name}}</p> -->
    `                  <hr class="sidebar-divider">
                          
                        </div>
                      </div>
                      {% endif %}
                      {% endfor %}
                  </li>
                  <!-- <li class="timeline-item bg-white rounded ml-3 mb-2 p-4 shadow">
                      <div class="timeline-arrow"></div>
                      <h2 class="h5 mb-0">Title of section 3</h2><span class="small text-gray"><i class="fa fa-clock-o mr-1"></i>18 August, 2019</span>
                      <p class="text-small mt-2 font-weight-light">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque scelerisque diam non nisi semper, et elementum lorem ornare. Maecenas placerat facilisis mollis. Duis sagittis ligula in sodales vehicula....</p>
                  </li>
                  <li class="timeline-item bg-white rounded ml-3 mb-2 p-4 shadow">
                      <div class="timeline-arrow"></div>
                      <h2 class="h5 mb-0">Title of section 4</h2><span class="small text-gray"><i class="fa fa-clock-o mr-1"></i>10 October, 2019</span>
                      <p class="text-small mt-2 font-weight-light">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque scelerisque diam non nisi semper, et elementum lorem ornare. Maecenas placerat facilisis mollis. Duis sagittis ligula in sodales vehicula....</p>
                      <p class="text-small mt-2 font-weight-light">Voluptatibus temporibus esse illum eum aspernatur, fugiat suscipit natus! Eum corporis illum nihil officiis tempore. Excepturi illo natus libero sit doloremque, laborum molestias rerum pariatur quam ipsam necessitatibus incidunt, explicabo.</p>
                  </li> -->
              </ul><!-- End -->

          </div>
      </div>

      <!-- Modal footer -->
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
      </div>

    </div>
  </div>
</div>

templates/skymarkPages/Dashboard/studentsAttendenceModal.html
<div class="modal fade" id="studentsAttendenceModal{{student.id}}">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="studentFeePayments"><code>{{student.student_full_name}}</code> is </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      
       <form action="" method="post">
       {% csrf_token %}
       <input type="text" name="student_name" id="" value="{{student.id}}" style="display: none;">
       {{form3.date.label}}
       {{form3.date}}
       <div class="form-group">
        <div class="button d-flex">
          <input type="submit" name="student_is_absent" value="student is absent" class="mt-4 mr-4 ">
          <input type="submit" name="student_is_present" value="student is present" class="mt-4  btn-outline-success">
        </div>
       </div>
  
       </form>
  
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-danger" data-dismiss="modal">close</button>
  
      </div>
    </div>
  </div>
  </div>
  